### ISSUE TITLE
SkidsDAO Home Page Text Edits 

### ISSUE THREAD

**Issue by m0ham3dx** [SkidsDAO/skidsdao.github.io#5]
# Issue Purpose / Description 

Recommended changes to the text [SkidsDAO About Page](https://skidsdao.github.io/about)

# Edits 

_Original_
> SkidsDAO is a hacker and cypherpunk collective with the objective of securing and improving the decentralised web. We achieve this through our work and contributions to public goods, inspiring, onboarding and mentoring security engineers and occassionally smart contract security reviews to projects we feel will have a positive effect on the ecosystem.

**EDIT**
SkidsDAO is a  hacker/[cypherpunk](https://en.wikipedia.org/wiki/Cyberpunk) collective interested in fortifying the security of the decentralized web. Our philosophy involves active contribution to [public goods](https://www.khanacademy.org/economics-finance-domain/microeconomics/market-failure-and-the-role-of-government/externalities-topic/a/public-goods-cnx), onboarding and collaborating with other security engineers & enthusiasts.  We are also very much interested in taking on _Smart Contract Auditing_ endeavors with those projects who have a positive impact on the decentralized ecosystem.

----

_Original_

> We love to have fun and prefer to keep things light hearted while perpetuating perfection in all that we do. Don’t want to end up stuffy and miserable after all. ;)

> Though we cultivate a light hearted environment, it is a meritocracy nonetheless as noted by the progressions systems we have in place. As a result of these efforts, we hope to churn out some of the greatest hackers the blockchain world will ever see.

> As always, we welcome all but only the 1337 have our respect. We’ll be waiting until you’re ready, anon.

**EDIT**

Our mental models is a mix of continuous results oriented experimentation, coupled with constant enthusiasm to keep things interesting. Of-course, even though light heartedness and playful-ness is a mandatory core component of our driving philosophy, we place a great deal of importance on merit and skill and strive to ensure that our interactions are a constant learning experience. 

We hope to bring into existence only the most l337 explorers of the cyber realms, who have a very high degree of ethical and moral concern in everything that they do eventually commanding respect !.  This is an open call to you anon, join us and be part of the transformation.

**Comment by 0xsomnus** [comment]
https://github.com/SkidsDAO/skidsdao.github.io/pull/6
